/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AdventureGame;

import org.junit.Test;
import static org.junit.Assert.*;
import model.*;
import controller.*;

public class AppTest {
	
	int[] progress;
	Inventory i = new Inventory();
    
@Test
public void HealthTest(){
	World world = new World();
	Player target = new Player(world, 20, this.progress, i);
	int health = target.getHealth() -1;
	target.reduceHealth(1);
	assertEquals(health, target.getHealth());
}
@Test
public void HealthDead(){
	World world = new World();
	Player target = new Player(world, 20, this.progress, i);
	target.reduceHealth(20);
	int health = target.getHealth();
	assertEquals(0, health);
}
@Test
public void EnemyTest(){
	World world = new World();
	Enemy target = new Enemy(world, 20);
	int health = target.getHealth() -1;
	target.reduceHealth(1);
	assertEquals(health, target.getHealth());
}
@Test
public void EnemyDead(){
	World world = new World();
	Enemy target = new Enemy(world, 20);
	target.reduceHealth(20);
	int health = target.getHealth();
	assertEquals(0, health);
}


}
